In [3]:
pip install beautifulsoup4

Requirement already satisfied: beautifulsoup4 in d:\data_analysis\anaconda3a\lib\site-packages (4.11.1)
Requirement already satisfied: soupsieve>1.2 in d:\data_analysis\anaconda3a\lib\site-packages (from beautifulsoup4) (2.3.2.post1)
Note: you may need to restart the kernel to use updated packages.

In [4]:
pip install requests

Requirement already satisfied: requests in d:\data_analysis\anaconda3a\lib\site-packages (2.28.1)
Requirement already satisfied: idna<4,>=2.5 in d:\data_analysis\anaconda3a\lib\site-packages (from requests) (3.4)
Requirement already satisfied: certifi>=2017.4.17 in d:\data_analysis\anaconda3a\lib\site-packages (from requests) (2022.6.15)
Requirement already satisfied: charset-normalizer<3,>=2 in d:\data_analysis\anaconda3a\lib\site-packages (from requests) (2.0.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in d:\data_analysis\anaconda3a\lib\site-packages (from requests) (1.26.12)
Note: you may need to restart the kernel to use updated packages.

In [7]:
import requests 
from bs4 import BeautifulSoup
from csv import writer
import pandas as pd
url="https://listado.mercadolibre.com.co/audifonos_Desde_51_NoIndex_True"
page = requests.get(url)
print(page)

<Response [200]>

In [8]:
soup = BeautifulSoup(page.content,'html.parser')
lists = soup.find_all('div',class_ = "ui-search-result__wrapper shops__result-wrapper")
stars = soup.find('span',class_ = 'ui-search-reviews__ratings')

In [9]:
#write a csv
#'star2','star3','star4','star5',star2,star3,star4,star5,
with open('prueba.csv', 'w', encoding = 'utf8', newline='') as f:
    thewriter = writer(f)
    header = ['Title', 'Price','Reviews','star1','star2','star3','star4','star5']
    thewriter.writerow(header)
    for list in lists:
        title = list.find('h2',class_ = "shops__item-title").text
        price = list.find('span',class_ = "price-tag-fraction").text
        reviews = list.find('span',class_= "ui-search-reviews__amount")
        for star in stars:
            star.use
            
        
        info = [title,price,reviews,star1,star2,star3,star4,star5]
        thewriter.writerow(info)

In [10]:
#iterate in multiple pages of the same search and, produce a csv
headphones_final = []
for i in range(51,1051,50):
    url = f"https://listado.mercadolibre.com.co/audifonos_Desde_{i}_NoIndex_True"
    page = requests.get(url)
    soup = BeautifulSoup(page.content,'html.parser')
    lists = soup.find_all('div',class_ = "ui-search-result__wrapper shops__result-wrapper")
    stars = soup.find('span',class_ = 'ui-search-reviews__ratings')

    for list in lists:
        title = list.find('h2',class_ = "shops__item-title").text
        price = list.find('span',class_ = "price-tag-fraction").text
        reviews = list.find('span',class_= "ui-search-reviews__amount")
        for star in stars:
            star.use
        headphones_final.append([title,price,reviews,star1,star2,star3,star4,star5])

In [11]:
df = pd.DataFrame(headphones_final,columns = ['Title','Price','Reviews','star1','star2','star3','star4','star5'])
df.head()

,Title,Price,Reviews,star1,star2,star3,star4,star5
0,Audifonos Deportivos Samsung Inalambricos Itfi...,95.900,None,[[]],[[]],[[]],[[]],[[]]
1,AirPods Serie 3 Y Pro Bluetooth Compatibles iP...,119.000,None,[[]],[[]],[[]],[[]],[[]]
2,Audífonos in-ear Xiaomi Mi Headphones Basic negro,27.821,[390],[[]],[[]],[[]],[[]],[[]]
3,Audífonos in-ear inalámbricos Xiaomi Redmi Air...,137.999,[286],[[]],[[]],[[]],[[]],[[]]
4,Audífonos in-ear KZ ZST with mic purple y blue,79.900,[167],[[]],[[]],[[]],[[]],[[]]

In [12]:
df.to_csv('headphones_final.csv')

In [13]:
df

,Title,Price,Reviews,star1,star2,star3,star4,star5
0,Audifonos Deportivos Samsung Inalambricos Itfi...,95.900,None,[[]],[[]],[[]],[[]],[[]]
1,AirPods Serie 3 Y Pro Bluetooth Compatibles iP...,119.000,None,[[]],[[]],[[]],[[]],[[]]
2,Audífonos in-ear Xiaomi Mi Headphones Basic negro,27.821,[390],[[]],[[]],[[]],[[]],[[]]
3,Audífonos in-ear inalámbricos Xiaomi Redmi Air...,137.999,[286],[[]],[[]],[[]],[[]],[[]]
4,Audífonos in-ear KZ ZST with mic purple y blue,79.900,[167],[[]],[[]],[[]],[[]],[[]]
...,...,...,...,...,...,...,...,...
1106,Diadema Quantum 200,289.900,None,[[]],[[]],[[]],[[]],[[]]
1107,Portatil Asus Vivobook X415ja I3 1005g1 8gb Ss...,1.999.900,None,[[]],[[]],[[]],[[]],[[]]
1108,Manos Libres Audifonos Samsung Akg S8 S9 S10 N...,44.000,None,[[]],[[]],[[]],[[]],[[]]
1109,Audífonos Inalámbricos Gamer Bluetooth Con Mic...,100.000,None,[[]],[[]],[[]],[[]],[[]]
1110,Audifonos Inalambricos 1hora Auriculares Bluet...,74.500,None,[[]],[[]],[[]],[[]],[[]]